#!/usr/bin/python

# turns xml export from keepassx into csv file, suitable for
# putting into a spreadsheet and printing

# Ryan Tucker 2009/03/19

import sys
import xml.etree.ElementTree as ET

try:
	filename = sys.argv[1]
except:
	print 'usage: ' + sys.argv[0] + ' filename'
	sys.exit(1)

outputdict = {}

tree = ET.parse(filename)

# The database level
elem = tree.getroot()
firstgroup = elem.getchildren()[0]

# General level
level1 = firstgroup.find('title').text

# get individual groups
for i in firstgroup.findall('group'):
	level2 = i.find('title').text
	# Get individual entries
	for j in i.findall('entry'):
		title = j.find('title').text
		username = j.find('username').text
		password = j.find('password').text
		if not username: username = ''	
		if not title: title = ''
		if not password: password = ''
		print '"' + level2 + '","' + title + '","' + username + '","' + password + '"'

